services:
  webapp:
    tty: true  # equivalent to -t
    stdin_open: true  # equivalent to -i
    command: >
      sh -c '
        echo "Skipping webapp server start and starting an interactive shell to allow for service start customization, debugger attachment etc. ...";
        exec bash;
      '
